bookstore/controllers/admin_routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, session
from models.book import Book
from models import db
from models.order import Order
from models.user import User

admin = Blueprint('admin', __name__)


@admin.route('/books')
def admin_books():
    """
    Allows a logged-in admin to see all books in the database
    """

    # If user is not logged in, redirect them to login page
    if 'UserID' not in session:
        flash('Please login to access admin view books')
        return redirect(url_for('user.login'))

    # This route only works for Admins
    if session['UserType'] != 'Admin':
        flash('You must be an admin to preform this operation')
        return redirect(url_for('main.index'))

    # Query for all books in the DB
    books = Book.query.all()
    return render_template('admin_books.html', books=books)


@admin.route('/edit_book/<int:book_id>', methods=['GET', 'POST'])
def edit_book(book_id):
    """
    Allows a logged-in admin to edit a book
    :param book_id: The primary key of the books database table
    """

    # If user is not logged in, redirect them to login page
    if 'UserID' not in session:
        flash('Please login to access admin view books')
        return redirect(url_for('user.login'))

    # This route only works for Admins
    if session['UserType'] != 'Admin':
        flash('You must be an admin to preform this operation')
        return redirect(url_for('main.index'))

    # Fetch the book from the database by its primary key
    book = Book.query.get(book_id)

    # If a non-existent BookID was searched for
    if not book:
        flash('Book not found!', 'danger')
        return redirect(url_for('admin.admin_books'))

    # User has submitted the edit book form
    if request.method == 'POST':
        # Update the database with the new book information
        book.Title = request.form['title']
        book.Author = request.form['author']
        book.Price = float(request.form['price'])
        book.Stock = int(request.form['stock'])
        db.session.commit()
        flash('Book updated successfully!', 'success')
        return redirect(url_for('admin.admin_books'))

    return render_template('edit_books.html', book=book)


@admin.route('/delete_book/<int:book_id>')
def delete_book(book_id):
    """
    Allows an admin to delete a book from the books table in the database
    :param book_id: The primary key of the Book table in the database representing the book to be deleted
    """
    # If user is not logged in, redirect them to login page
    if 'UserID' not in session:
        flash('Please login to access admin view books')
        return redirect(url_for('user.login'))

    # This route only works for Admins
    if session['UserType'] != 'Admin':
        flash('You must be an admin to preform this operation')
        return redirect(url_for('main.index'))

    # If a non-existent BookID was searched for
    book = Book.query.get(book_id)
    if not book:
        flash('Book not found!', 'danger')
        return redirect(url_for('admin.admin_books'))

    # Delete the book from the database
    book.OutOfPrint = True
    db.session.commit()
    flash('Book deleted successfully!', 'success')
    return redirect(url_for('admin.admin_books'))


@admin.route('/restore_book/<int:book_id>')
def restore_book(book_id):
    """
    Allows an admin to restore a deleted book from the books table in the database
    :param book_id: The primary key of the Book table in the database representing the book to be deleted
    """
    # If user is not logged in, redirect them to login page
    if 'UserID' not in session:
        flash('Please login to access admin view books')
        return redirect(url_for('user.login'))

    # This route only works for Admins
    if session['UserType'] != 'Admin':
        flash('You must be an admin to preform this operation')
        return redirect(url_for('main.index'))

    # If a non-existent BookID was searched for
    book = Book.query.get(book_id)
    if not book:
        flash('Book not found!', 'danger')
        return redirect(url_for('admin.admin_books'))

    # Delete the book from the database
    book.OutOfPrint = False
    db.session.commit()
    flash('Book restored successfully!', 'success')
    return redirect(url_for('admin.admin_books'))



@admin.route('/all_orders')
def all_orders():
    """
    Allows an admin to see all orders, and find the total sales value
    """
    # If user is not logged in, redirect them to login page
    if 'UserID' not in session:
        flash('Please login to access admin view all orders')
        return redirect(url_for('user.login'))

    # This route only works for Admins
    if session['UserType'] != 'Admin':
        flash('You must be an admin to preform this operation')
        return redirect(url_for('main.index'))

    # Query the database for all orders, joining the user data
    orders = db.session.query(Order, User).join(User).filter(Order.UserID == User.UserID)

    return render_template('all_orders.html', orders=orders)

bookstore/controllers/book_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from models import db
from models.book import Book
from models.order import Order

book_routes = Blueprint('book', __name__)


@book_routes.route('/add_book', methods=['GET', 'POST'])
def add_book():
    """
    Allows a logged-in user to add new books to the bookstore database.
    """

    # If user is not logged in, redirect them to login page
    if 'UserID' not in session:
        flash('Please login to add books')
        return redirect(url_for('user.login'))

    if session['UserType'] != 'Admin':
        flash('You must be an admin to preform this operation')
        return redirect(url_for('main.index'))

    # If user submits a new book through the form, persist it to the database and redirect to the dashboard
    if request.method == 'POST':
        new_book = Book(
            Title=request.form['title'],
            Author=request.form['author'],
            Price=request.form['price'],
            Stock=request.form['stock']
        )
        db.session.add(new_book)
        db.session.commit()
        return redirect(url_for('main.dashboard'))

    # If the user landed on the add book form
    return render_template('add_book.html')


@book_routes.route('/order_book/<int:book_id>', methods=['GET', 'POST'])
def order_book(book_id):
    """
    Allows a user to order a book.
    This will subtract the order quantity from the stock and create an order for the user.
    :param book_id: The primary key of a row in the book database table
    """

    # If user is not logged in, redirect them to login page
    if 'UserID' not in session:
        flash('Please login to order books', 'danger')
        return redirect(url_for('user.login'))

    book = Book.query.get(book_id)

    # If the book_id passed in through the URL doesn't match any book
    # in the database, return an error and redirect to the book index
    if not book:
        flash('Book not found!', 'danger')
        return redirect(url_for('book.index'))

    # If the user is submitting an order through the order book form:
    # Verify quantity ordered is within bounds
    # If so, subtract quantity from book stock and persist that change to the database
    # Then redirect to the order book page
    if request.method == 'POST':
        quantity = int(request.form['quantity'])
        if quantity <= 0:
            flash('You must order a minimum of 1 book', 'danger')
            return redirect(url_for('book.order_book', book_id=book_id))
        if quantity > book.Stock:
            flash('Not enough stock available!', 'danger')
            return redirect(url_for('book.order_book', book_id=book_id))
        
        new_order = Order(UserID=session['UserID'], BookID=book_id, Quantity=quantity)
        book.Stock -= quantity
        db.session.add(new_order)
        db.session.commit()
        flash('Book ordered successfully!', 'success')
        return redirect(url_for('main.dashboard'))

    # If the user landed on the order book form
    return render_template('order_book.html', book=book)

bookstore/controllers/main_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from werkzeug.security import generate_password_hash

from models import db
from models.user import User
from models.book import Book

main = Blueprint('main', __name__)


@main.route('/')
def index():
    """
    Home page of the bookstore
    """

    # Only show books on the storefront that have inventory
    books = Book.query.filter(Book.Stock >= 1).filter(Book.OutOfPrint == False)
    return render_template('index.html', books=books)


@main.route('/all_users')
def all_users():
    """
    Allows an administrator to see all users in the user table of the database
    """
    # If user is not logged in, redirect them to login page
    if 'UserID' not in session:
        flash('Please login to access admin view books')
        return redirect(url_for('user.login'))

    # This route only works for Admins
    if session['UserType'] != 'Admin':
        flash('You must be an admin to preform this operation')
        return redirect(url_for('main.index'))

    # Fetch all users from the database
    users = User.query.all()
    return render_template('all_users.html', users=users)


@main.route('/reset_password', defaults={'user_id': None}, methods=['GET', 'POST'])
@main.route('/reset_password/<int:user_id>', methods=['GET', 'POST'])
def reset_password(user_id):
    """
    Allows users to reset their own passwords, and allow admins to reset anyone's password
    :param user_id: Optional: The primary key of the user DB table representing the user to have their password reset
    """
    # If user is not logged in, redirect them to login page
    if 'UserID' not in session:
        flash('Please login to reset password')
        return redirect(url_for('user.login'))

    # Default to resetting your own password, unless indicated in the URL
    if user_id is None:
        user_id = session['UserID']

    # Customers can only reset their own passwords
    if session['UserType'] == 'Customer' and user_id != session['UserID']:
        flash('You can only try to change your own password.')
        return redirect(url_for('main.index'))

    # The user has submitted the password reset form
    if request.method == 'POST':
        # Fetch the specified user from the database and update the row with the new password
        password_reset_user = User.query.get(user_id)
        password_reset_user.Password = generate_password_hash(request.form['password'], method='scrypt')
        db.session.commit()

        # Don't log out admins when they reset another user's password
        if session['UserType'] == 'Admin':
            return redirect(url_for('main.dashboard'))
        else:
            return redirect(url_for('user.logout'))

    return render_template('reset_password.html', user_id=user_id)


@main.route('/dashboard')
def dashboard():
    """
    A dashboard of links to navigate the user to order history, profile, password reset, etc.
    Admins see more options than users do and can also edit the bookstore contents.
    """
    if 'UserID' in session:
        user = User.query.filter_by(UserID=session['UserID']).first()
        return render_template('dashboard.html', user=user)
    return redirect(url_for('user.login'))

bookstore/controllers/user_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from werkzeug.security import generate_password_hash, check_password_hash
from models.user import User
from models.order import Order
from models import db

user = Blueprint('user', __name__)


@user.route('/register', methods=['POST', 'GET'])
def register():
    """
    Allow an unauthenticated visitor to create a new Customer account
    """

    # The visitor submitted the registration form
    if request.method == 'POST':
        # Hash the provided password for security
        hashed_pw = generate_password_hash(request.form['password'], method='scrypt')

        # Create a new user row in the database
        new_user = User(Name=request.form['name'], Email=request.form['email'], Password=hashed_pw)
        db.session.add(new_user)
        db.session.commit()
        flash('Registration successful. Please log in.', 'success')
        return redirect(url_for('user.login'))
    return render_template('register.html')


@user.route('/login', methods=['POST', 'GET'])
def login():
    """
    Allow a visitor with a valid email address / password to log in.
    This sets session variables in a browser cookie to persist the login status after closing and re-opening a tab
    """

    # Visitor has submitted the login form
    if request.method == 'POST':

        # Search for the user corresponding to the provided email address in the database
        user = User.query.filter_by(Email=request.form['email']).first()

        # If the email address exists in the database and the hash of the provided password matches, set session
        if user and check_password_hash(user.Password, request.form['password']):
            session['UserID'] = user.UserID
            session['UserEmail'] = user.Email
            session['UserType'] = user.UserType
            session['UserName'] = user.Name
            flash('Logged in successfully!', 'success')
            return redirect(url_for('main.index'))
        flash('Invalid email or password. Please try again.', 'danger')
    return render_template('login.html')


@user.route('/logout')
def logout():
    """
    Deletes session variables, requiring a user whom visits this page to log back in
    """
    session.pop('UserID', None)
    session.pop('UserEmail', None)
    session.pop('UserName', None)
    session.pop('UserType', None)
    flash('Logged out successfully.', 'success')
    return redirect(url_for('main.index'))


@user.route('/profile', methods=['GET', 'POST'])
def profile():
    """
    Allows a user to view/edit their name and email address
    """
    if 'UserID' not in session:
        flash('Please login to view profile', 'danger')
        return redirect(url_for('user.login'))

    #  Fetch the logged in user's ID from the session cookie
    user = User.query.get(session['UserID'])

    # User has submitted the user profile form
    if request.method == 'POST':

        # Update the user's row in the database with the new values
        user.Name = request.form['name']
        user.Email = request.form['email']
        db.session.commit()
        flash('Profile updated successfully!', 'success')
        return redirect(url_for('user.profile'))

    return render_template('profile.html', user=user)


@user.route('/my_orders')
def my_orders():
    """
    Allows a user to see the orders they placed
    """
    if 'UserID' not in session:
        flash('Please login to view your orders', 'danger')
        return redirect(url_for('user.login'))

    # Query the database for all orders that belong to the signed-in user
    orders = Order.query.filter_by(UserID=session['UserID']).all()
    return render_template('my_orders.html', orders=orders)

bookstore/templates/add_book.html
{% extends "layout.html" %}

{% block content %}
<h2>Add Book</h2>
<form action="{{ url_for('book.add_book') }}" method="post">
    <div class="form-group">
        <label>Title:</label>
        <input type="text" class="form-control" name="title" required>
    </div>
    <div class="form-group">
        <label>Author:</label>
        <input type="text" class="form-control" name="author" required>
    </div>
    <div class="form-group">
        <label>Price:</label>
        <input type="number" step="0.01" class="form-control" name="price" required>
    </div>
    <div class="form-group">
        <label>Stock:</label>
        <input type="number" class="form-control" name="stock" required>
    </div>
    <button type="submit" class="btn btn-primary">Add Book</button>
</form>
{% endblock %}

bookstore/templates/admin_books.html
{% extends "layout.html" %}

{% block content %}
<h2>Manage Books</h2>
<ul class="list-group">
{% for book in books %}
    <li class="list-group-item">
        {{ book.Title }} by {{ book.Author }}
        <a href="{{ url_for('admin.edit_book', book_id=book.BookID) }}" class="btn btn-warning btn-sm float-right ml-2">Edit</a>
        {% if book.OutOfPrint %}
            <a href="{{ url_for('admin.restore_book', book_id=book.BookID) }}" class="btn btn-danger btn-sm float-right">Restore</a>
        {% else  %}
            <a href="{{ url_for('admin.delete_book', book_id=book.BookID) }}" class="btn btn-danger btn-sm float-right">Delete</a>
        {% endif %}
    </li>
{% endfor %}
</ul>
{% endblock %}

bookstore/templates/all_orders.html
{% extends "layout.html" %}

{% block content %}
<h2>All Orders</h2>
<ul class="list-group">
{% for order in orders %}
    <li class="list-group-item">
        Book ID: {{ order.Order.BookID }} | Quantity: {{ order.Order.Quantity }} | User: {{ order.User.Email }}
    </li>
{% endfor %}
{% if not orders %}
    <li class="list-group-item">
        There have been no orders yet.
    </li>
{% endif %}
</ul>
{% endblock %}

bookstore/templates/all_users.html
{% extends "layout.html" %}

{% block content %}
<h2>All Users</h2>
<ul class="list-group">
{% for user in users %}
    <li class="list-group-item">
        {{ user.Name }} ({{ user.Email }})
        <a href="{{ url_for('main.reset_password')}}/{{  user.UserID  }}">
            <button type="submit" class="btn btn-primary">Reset Password</button>
        </a>
    </li>
{% endfor %}
</ul>
{% endblock %}

bookstore/templates/dashboard.html
{% extends "layout.html" %}

{% block content %}
    <h2>Dashboard - Welcome, {{ user.Name }}</h2>
    {%  if user.UserType == 'Customer'  %}
        <a href="{{ url_for('book.add_book') }}" class="btn btn-primary">Add Book (This shouldn't be here)</a>
    {%  endif  %}
    <a href="{{ url_for('user.my_orders') }}" class="btn btn-secondary">My Orders</a>
    <a href="{{ url_for('user.profile') }}" class="btn btn-info">Profile</a>
    <a href="{{ url_for('main.reset_password') }}" class="btn btn-dark">Reset Password</a>
{% if user.UserType == 'Admin' %}
    <a href="{{ url_for('book.add_book') }}" class="btn btn-primary">Add Book</a>
    <a href="{{ url_for('admin.admin_books') }}" class="btn btn-warning">Manage Books</a>
    <a href="{{ url_for('admin.all_orders') }}" class="btn btn-secondary">All Orders</a>
    <a href="{{ url_for('main.all_users') }}" class="btn btn-danger">All Users</a>
{% endif %}
{% endblock %}

bookstore/templates/edit_books.html
{% extends "layout.html" %}

{% block content %}
<h2>Edit Book - {{ book.Title }}</h2>

<form action="{{ url_for('admin.edit_book', book_id=book.BookID) }}" method="post">
    <div class="form-group">
        <label>Title:</label>
        <input type="text" class="form-control" name="title" value="{{ book.Title }}" required>
    </div>
    <div class="form-group">
        <label>Author:</label>
        <input type="text" class="form-control" name="author" value="{{ book.Author }}" required>
    </div>
    <div class="form-group">
        <label>Price:</label>
        <input type="number" step="0.01" class="form-control" name="price" value="{{ book.Price }}" required>
    </div>
    <div class="form-group">
        <label>Stock:</label>
        <input type="number" class="form-control" name="stock" value="{{ book.Stock }}" required>
    </div>
    <button type="submit" class="btn btn-primary">Update Book</button>
</form>
{% endblock %}

bookstore/templates/index.html
{% extends "layout.html" %}

{% block content %}
    <h2>Available Books</h2>
    <ul class="list-group">
    {% for book in books %}
        <li class="list-group-item">
            {{ book.Title }} by {{ book.Author }}
            <a href="{{ url_for('book.order_book', book_id=book.BookID) }}" class="btn btn-primary btn-sm float-right">Order</a>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

bookstore/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <title>Bookstore</title>
    <!-- Include Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

    <!-- Include Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="{{url_for('static', filename='script.js')}}"></script>

    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <script src="{{ url_for('static', filename='script.js') }}" defer></script>
</head>

<body onload="showFlashedMessagesModal()">

{#If Flask has sent flashed messages, show them with a Bootstrap modal#}
{% with messages = get_flashed_messages() %}
  {% if messages %}
    {% for message in messages %}
        <div class="modal fade" id="flashedMessagesModal" tabindex="-1">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                  <span>&times;</span>
                </button>
              </div>
              <div class="modal-body">
                  {{ message }}
              </div>
            </div>
          </div>
        </div>
    {% endfor %}
  {% endif %}
{% endwith %}

<header class="bg-dark text-white p-4 text-center">
    <a href="{{ url_for('main.index') }}">
        <button type="button" class="btn btn-primary">Home</button>
    </a>
    {%  if 'UserID' in session %}
        <a href="{{ url_for('main.dashboard') }}">
            <button type="button" class="btn btn-primary">Dashboard</button>
        </a>
        <a href="{{ url_for('user.logout') }}">
            <button type="button" class="btn btn-primary">Log Out</button>
        </a>
    {% else %}
        <a href="{{ url_for('user.login') }}">
            <button type="button" class="btn btn-primary">Log In</button>
        </a>
    {% endif %}
    <h1>Welcome to Bookstore</h1>
</header>

<div class="container mt-4">
    {% block content %}{% endblock %}
</div>

<footer class="bg-dark text-white text-center p-4 mt-5">
    &copy; 2023 Bookstore Inc.
</footer>


</body>
</html>

bookstore/templates/login.html
{% extends "layout.html" %}

{% block content %}
<h2>Login</h2>
<form action="{{ url_for('user.login') }}" method="post">
    <div class="form-group">
        <label>Email:</label>
        <input type="email" class="form-control" name="email" required>
    </div>
    <div class="form-group">
        <label>Password:</label>
        <input type="password" class="form-control" name="password" required>
    </div>
    <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

bookstore/templates/my_orders.html
{% extends "layout.html" %}

{% block content %}
<h2>My Orders</h2>
<ul class="list-group">
{% for order in orders %}
    <li class="list-group-item">
        Book ID: {{ order.BookID }} | Quantity: {{ order.Quantity }}
    </li>
{% endfor %}
</ul>
{% endblock %}

bookstore/templates/order_book.html
{% extends "layout.html" %}

{% block content %}
<h2>{{ book.Title }} by {{ book.Author}}</h2>
<form action="{{ url_for('book.order_book', book_id=book.BookID) }}" method="post">
    {% if book.Stock == 0 %}
        <div class="form-group">
            <label>Quantity:</label>
                Out of stock
        </div>
    {% else %}
        <div class="form-group">
            <label>Quantity:</label>
            <input type="number" class="form-control" name="quantity" required>
        </div>
        <button type="submit" class="btn btn-primary">Order Book</button>
        {% endif %}
</form>
{% endblock %}

bookstore/templates/profile.html
{% extends "layout.html" %}

{% block content %}
<h2>Profile</h2>
<form action="{{ url_for('user.profile') }}" method="post">
    <div class="form-group">
        <label>Name:</label>
        <input type="text" class="form-control" name="name" value="{{ user.Name }}" required>
    </div>
    <div class="form-group">
        <label>Email:</label>
        <input type="email" class="form-control" name="email" value="{{ user.Email }}" required>
    </div>
    <button type="submit" class="btn btn-primary">Update Profile</button>
</form>
{% endblock %}

bookstore/templates/register.html
{% extends "layout.html" %}

{% block content %}
<h2>Register</h2>
<form action="{{ url_for('user.register') }}" method="post">
    <div class="form-group">
        <label>Name:</label>
        <input type="text" class="form-control" name="name" required>
    </div>
    <div class="form-group">
        <label>Email:</label>
        <input type="email" class="form-control" name="email" required>
    </div>
    <div class="form-group">
        <label>Password:</label>
        <input type="password" class="form-control" name="password" required>
    </div>
    <button type="submit" class="btn btn-primary">Register</button>
</form>
{% endblock %}

bookstore/templates/rest_password.html
{% extends "layout.html" %}

{% block content %}
<h2>Reset Password</h2>
<form action="{{ url_for('main.reset_password')}}/{{  user_id  }}" method="post">
    <div class="form-group">
        <label>New Password:</label>
        <input type="password" class="form-control" name="password" value="" required>
    </div>
    <button type="submit" class="btn btn-primary">Reset Password</button>
</form>
{% endblock %}